# Generated by Django 4.2.9 on 2024-07-16 17:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseLessonQuiz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Course_Level', models.CharField(max_length=255)),
                ('Categoria_Lesson', models.CharField(max_length=255)),
                ('Lesson_Content', models.CharField(max_length=255)),
                ('Topic_Father', models.CharField(max_length=255)),
                ('Topic_Son', models.CharField(default='Generico', max_length=255)),
                ('Quiz_Name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='QuizContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Spanish', models.TextField()),
                ('English', models.TextField()),
                ('FK_Course_Lesson_Quiz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quiz_builder.courselessonquiz')),
            ],
        ),
        migrations.CreateModel(
            name='UserAnswerScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Score', models.IntegerField(default=5)),
                ('FK_Quiz_Content', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quiz_builder.quizcontent')),
                ('FK_Table_Quiz_Course_Level', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quiz_builder.courselessonquiz')),
                ('Usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
