# Generated by Django 4.2.9 on 2024-07-16 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ListTopicFather',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('topic_father', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='StructuredEnglishGrammarCourse',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('courses', models.CharField(max_length=255)),
                ('lesson', models.CharField(max_length=255)),
                ('lesson_content', models.TextField()),
            ],
        ),
    ]
