# Generated by Django 4.2.9 on 2024-07-21 22:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('content_management', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ListTopicSon',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('topic_son', models.CharField(max_length=255)),
                ('topic_father', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='content_management.listtopicfather')),
            ],
        ),
    ]
